# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Phone_Number', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Played', models.BooleanField(default=False)),
                ('Score', models.IntegerField(default=0)),
                ('SolvedQns', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default='', max_length=1000)),
                ('Option_1', models.CharField(default='', max_length=100)),
                ('Option_2', models.CharField(default='', max_length=100)),
                ('Option_3', models.CharField(default='', max_length=100)),
                ('Option_4', models.CharField(default='', max_length=100)),
                ('Correct_Answer', models.IntegerField(default=0)),
                ('Difficulty', models.IntegerField(default=1)),
            ],
        ),
    ]
