# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ori_site', '0002_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Score',
            field=models.FloatField(default=0),
        ),
    ]
