# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori_site', '0003_auto_20170729_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Lives',
            field=models.IntegerField(default=3),
        ),
    ]
