# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori_site', '0004_profile_lives'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ConsideredScore',
            field=models.FloatField(default=0),
        ),
    ]
